# Generated by Django 4.0.4 on 2022-08-13 03:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='autoslug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Title', unique=True),
        ),
    ]
