# Generated by Django 4.0.4 on 2022-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Mails',
            field=models.CharField(max_length=50),
        ),
    ]
