# Generated by Django 4.0.4 on 2022-08-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_mails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Mails',
            field=models.CharField(max_length=60),
        ),
    ]
