# Generated by Django 4.0.4 on 2022-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.CharField(max_length=60)),
                ('Title', models.CharField(max_length=60)),
                ('Description', models.TextField()),
            ],
        ),
    ]
